=== sceptics-tool/sceptics-tool/res/asset.dtd
<!ELEMENT assets (asset+)>
<!ELEMENT asset (nodes+,data_types,data_profiles)>
<!ELEMENT nodes (name)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT data_types (type+)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT data_profiles (profile+)>
<!ELEMENT profile (#PCDATA)>

=== sceptics-tool/sceptics-tool/res/assets.xml
<?xml version="1.0"?>
<!DOCTYPE assets SYSTEM "asset.dtd">
<assets>
  <asset>
    <nodes>
      <name>EVC</name>
    </nodes>
    <data_types>
      <type>authenticated</type>
      <type>position</type>
      <type>data</type>
      <type>cvss</type>
    </data_types>
    <data_profiles>
      <profile>cvss</profile>
    </data_profiles>
  </asset> 
</assets>
